### ISSUE TITLE
Tinypng plugin seems that doesn't work on wintercms 1.2

### ISSUE THREAD

**Issue by haralake** [wintercms/wn-tinypng-plugin#1]
I installed succesfully plugin from backend. Then i enter on my .env file my API key:
TINYPNG_API_KEY=................. ....  ....  ..

but i get error:
`Class "Tinify\Tinify" not found
`
So i enter my key on:
plugins/winter/tinypng/config/config.php

and i don't get any error on frontend. But the problem is that plugin is not working. I try to insert new images using | resize() filter but as i see on my tinypng dashboard no image is optimized.

**Comment by LukeTowers** [comment]
@haralake did you install the plugin via composer?

**Comment by haralake** [comment]
You have pointed me in the right direction with your question. I installed through composer and it works without any problems. I wanted to try to install it from the backend, but apparently it's not ready yet. Thanks for the support.

**Comment by LukeTowers** [comment]
Yeah, I would avoid installing any plugins through the backend, that uses the old marketplace API wrapper and it's not very functional at the moment as we work on rebuilding the marketplace.

**Comment by LukeTowers** [comment]
@bennothommo can you do a tag sync on this repo?
